name: Pull Request Action
on:
  push:
    branches:
      - a/*
permissions:
  contents: write
  pull-requests: write

jobs:
  AddRecord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: |
            build-users-group =
            experimental-features = nix-command flakes

      - name: Install Python
        run: |
          nix-env -iA python311 -f https://github.com/tywtyw2002/nx-direct/tarball/nx

      - name: Checkout store
        uses: actions/checkout@v4
        with:
          path: ./store
          ref: store

      - name: Checkout build_dst
        uses: actions/checkout@v4
        with:
          path: ./dest
          ref: public

      - name: Add record
        run: |
          python3.11 ./ci.py --addjson -a ./ -r ./store/current -d ./dest

      - name: Delete branch
        run: |
          # echo ${{ github.ref }}
          # echo ${{ github.ref_name }}
          gh api --method DELETE "repos/${{ github.repository }}/git/refs/heads/${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to public
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dest
          branch: public
          clean: true
          single-commit: true

      - name: Push to store
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: store
          branch: store

